rm -rf arch/arm64/kernel/vdso32/sigreturn.o
rm -rf kernel/printk/printk.o
rm -rf kernel/time/posix-cpu-timers.o
rm -rf fs/ext4/extents.o
rm -rf crypto/xts.o
rm -rf fs/sdfat/*.o
rm -rf drivers/base/core.o
rm -rf drivers/base/power/opp/core.o
rm -rf drivers/base/regmap/regcache-rbtree.o
rm -rf drivers/char/random.o
rm -rf drivers/char/diag/diagchar_core.o
rm -rf drivers/char/diag/diag_dci.o
rm -rf drivers/gpu/drm/drm_edid.o
rm -rf techpack/audio/asoc/msm-pcm-routing-v2.o
rm -rf techpack/audio/asoc/msm-audio-effects-q6-v2.o
rm -rf techpack/audio/asoc/msm-dts-srs-tm-config.o
rm -rf techpack/audio/asoc/codecs/tas2557/tas2557-core.o
rm -rf techpack/audio/asoc/codecs/wcd9xxx-common-v2.o
rm -rf techpack/audio/dsp/q6afe.o
rm -rf drivers/gpu/drm/msm/sde/sde_hw_rot.o
rm -rf drivers/gpu/drm/msm/sde/sde_encoder_phys_wb.o
rm -rf techpack/audio/dsp/codecs/amrwb_in.o
rm -rf techpack/audio/ipc/apr.o
rm -rf drivers/gpu/msm/kgsl_pwrctrl.o
rm -rf drivers/gpu/msm/kgsl_pwrscale.o
rm -rf drivers/gpu/msm/kgsl_events.o
rm -rf drivers/gpu/msm/adreno_dispatch.o
rm -rf net/bluetooth/hci_request.o
