name: Build kermel
on: 
  push: 

jobs:
  build_kermel:
    runs-on: ubuntu-latest
    env:
      BOT_API_KEY: ${{ secrets.BOT_API_KEY }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      GITHUB_REPO: ${{ github.repository }}
      GITHUB_REFNAME: ${{ github.ref_name }}
    steps:
      - name: update cache on every commit
        uses: actions/cache@v3
        with:
          path: |
            beryllium
          key: beryllium-${{ github.ref_name }}-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            beryllium-${{ github.ref_name }}-${{ runner.os }}
      - name: Build kermel
        run: |
             export TZ='Asia/Kolkata' && date
             #rm -rf beryllium
             cd beryllium && git fetch origin && git checkout origin/$GITHUB_REFNAME && git branch -D $GITHUB_REFNAME && git checkout -b $GITHUB_REFNAME && git branch || { git clone https://github.com/$GITHUB_REPO -b $GITHUB_REFNAME beryllium && cd beryllium && git branch ;}
             ls
             #make clean && make mrproper
             #bash rm.sh
             bash build_kernel.sh
