name: Build kermel
on: 
  push: 

jobs:
  build_kermel:
    runs-on: ubuntu-latest
    env:
      BOT_API_KEY: ${{ secrets.BOT_API_KEY }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      GITHUB_REPO: ${{ github.repository }}
      GITHUB_REFNAME: ${{ github.ref_name }}
    steps:
      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            beryllium
            #ccberyllium
          key: beryllium-${{ github.ref_name }}-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            beryllium-${{ github.ref_name }}-${{ runner.os }}
      - name: Clone
        if: steps.cache.outputs.cache-hit != 'false'
        run: |
          git clone --depth 1 https://github.com/$GITHUB_REPO -b $GITHUB_REFNAME beryllium && cd beryllium && git branch && git reset --hard || cd beryllium
      - name: Update
        if: steps.cache.outputs.cache-hit == 'false'
        run: |
          cd beryllium && git fetch --depth 1 origin $GITHUB_REFNAME && git checkout origin/$GITHUB_REFNAME && git branch -D $GITHUB_REFNAME && git checkout -b $GITHUB_REFNAME && git branch && git reset --hard
      - name: Add pkgs
        run: |
          sudo apt-get update
          sudo apt-get install ccache pigz -y
      - name: Build
        run: |
          export TZ='Asia/Kolkata' && date
          cd beryllium && ls && git status
          #ccache -d ../ccberyllium -vs
          #ccache -d ../ccberyllium -cC
          #ccache -d ../ccberyllium -vs
          bash build_kernel.sh
          #ccache -d ../ccberyllium -vs
          time { make clean && make mrproper ;}
          rm -rf kernelzip
          rm -rf bl-*.txt
          rm -rf wbl-*.txt
          rm -rf simple-beryllium*.zip
